image: julia:1.4     

variables:
  MOFFITT_CERTS: "/etc/gitlab-runner/certs/moffitt-ca.crt /etc/gitlab-runner/certs/moffitt-ca-int.crt /etc/gitlab-runner/certs/moffitt-chain"

before_script:
  - mkdir /usr/local/share/ca-certificates/moffitt
  - cp $MOFFITT_CERTS /usr/local/share/ca-certificates/moffitt/ && update-ca-certificates
  - julia --project=@. -e "import Pkg; Pkg.build()"

default:
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = true)"
    - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    #- julia --project=test/coverage test/coverage/coverage-summary.jl

pages:
  stage: deploy
  script:
    - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
    - julia --project=docs --color=yes docs/make.jl
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
  - develop
